FROM jupyterhub/systemuser

# Clean up from existing systemuser setup
RUN rm -rf /home/jovyan

# Install mysql-related packages
RUN apt-get update && apt-get install -y libmysqlclient-dev && rm -rf /var/lib/apt/lists/*
RUN /opt/conda/bin/pip install --egg mysql-connector-python-rf

# Install featurefactory into site-packages
# TODO make this not python3.5 hardcoded
WORKDIR /opt/conda/lib/python3.5/site-packages
COPY requirements.txt requirements.txt
RUN /opt/conda/bin/pip install -r requirements.txt
COPY src featurefactory
WORKDIR featurefactory
RUN /opt/conda/bin/python setup.py install

# Same as jupyterhub/systemuser
CMD ["sh", "/srv/singleuser/systemuser.sh"]
