FROM jupyterhub/systemuser:0.6.0

# Clean up from existing systemuser setup
RUN rm -rf /home/jovyan

# Upgrade package managers
RUN apt-get update
RUN /opt/conda/bin/pip install --upgrade pip

# Install mysql-related packages
RUN apt-get install -y libmysqlclient-dev

# Install autosklearn
RUN apt-get install -y build-essential gcc
RUN /opt/conda/bin/conda install -y swig libgcc
#RUN /opt/conda/bin/pip install --no-cache-dir -v xgboost==0.4a30
RUN wget -q -O- https://raw.githubusercontent.com/automl/auto-sklearn/v.0.2.0/requirements.txt | xargs -n 1 -L 1 /opt/conda/bin/pip install
RUN /opt/conda/bin/pip install auto-sklearn==0.2.0

# Reduce size of final image
RUN rm -rf /var/lib/apt/lists/*

# Install featurefactory into site-packages
# TODO make this not python3.5 hardcoded
WORKDIR /opt/conda/lib/python3.5/site-packages
COPY requirements.txt requirements.txt
RUN /opt/conda/bin/pip install -r requirements.txt
COPY src featurefactory
WORKDIR featurefactory
RUN /opt/conda/bin/python setup.py install

# Same as jupyterhub/systemuser
CMD ["sh", "/srv/singleuser/systemuser.sh"]
